### PR TITLE
dnswl: add optional dnswl.org based auto whitelisting

### PR DESCRIPTION
**Pull request by fishman**
Updated the mailinabox submitted patch to allow for
the dnswl option to be optional

### CODE REVIEW

**Comment by fishman** [comment]
Can you restart the build? There were timeout issues on travis when I submitted this PR

**Comment by fishman** [comment]
any change you can get this merged?

**Comment by schweikert** [comment]
Hi Reza,

Sorry for the late reaction from me... I really appreciate you doing a contribution to Postgrey, but as was also explained in #12, doing synchronous DNS resolution during a client request is a bad idea from a performance point of view, because postgrey is designed to work in a single thread in a non-blocking way. If this really would need to be integrated, it would need to use some sort of asynchronous implementation, but it would require a big code refactor.

**Comment by fishman** [comment]
In your comment you said you don't like it because it isn't optional though. This is optional and disabled by default with a warning about the implication. So it addresses what you asked for in there.

**Comment by Ka-Hen** [comment]
Found this old thread and I think it's better to let Postfix do the check:

smtpd_recipient_restrictions = permit_dnswl_client list.dnswl.org, ....

https://www.dnswl.org/?page_id=15#postfix

**Pull request closed without merging**
